# Generated by Django 5.2.9 on 2026-03-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view', 'Can view MAST pages'), ('can_submit_plans', 'Can submit observation plans'), ('can_manage_plans', 'Can manage plans'), ('can_execute_plans', 'Can execute plans and batches'), ('can_use_controls', 'Can use low-level controls'), ('can_change_configuration', 'Can change configuration'), ('can_manage_users', 'Can manage users')]},
        ),
    ]
