# Generated by Django 5.2.9 on 2026-03-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_email_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_registered',
        ),
    ]
